export const COMPRESSIBLE_CONTENT_TYPES = {
  "application/atom_xml": true,
  "application/javascript": true,
  "application/json": true,
  "application/rss+xml": true,
  "application/vnd.ms-fontobject": true,
  "application/x-font-opentype": true,
  "application/x-font-ttf": true,
  "application/x-javascript": true,
  "application/xhtml+xml": true,
  "application/xml": true,
  "application/xml+rss": true,
  "image/svg+xml": true,
  "image/x-icon": true,
  "text/css": true,
  "text/html": true,
  "text/javascript": true,
  "text/plain": true,
};
